use_frameworks!

target 'TaCoPopulator_Example' do
  pod 'TaCoPopulator', :path => '../'

  target 'TaCoPopulator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
  pod 'Nimble', '~> 7.0'
  end
end
